### ISSUE TITLE
 Recommendation to look into Nike Running Cluj

### ISSUE THREAD

**Issue by danutdaian** [Ughuuu/Sports-Organiser-Issues#1]
Check Nike Running Club.

**Comment by Clannin** [comment]
Punctul foarte al paginii este faptul ca se fac foarte repede placuți pentru ultizilatori noi si chiar și pentru cei vechi, datorită faptului ca au multe poze pe care le imbina cu putin scris (o mică descriere); totodată adaugă din cand în cand conținut nou pe pagină.
